### ISSUE TITLE
MITRE data sources not showing up

### ISSUE THREAD

**Issue by roboticsea** [rabobank-cdc/DeTTECT#121]
I've tried running this locally and from the web app you guys host, but for whatever reason we are getting this.
<img width="696" alt="Screenshot 2024-11-04 at 12 53 11 PM" src="https://github.com/user-attachments/assets/fb45d735-761e-4045-8134-8146d2f0d130">

The image is when you try to Add All Data Sources.  Where's the MITRE?  :)

**Comment by rahulgk-mettle** [comment]
I'm also facing some issues with the datasources. Seems like there was an update to the [editor source files](https://github.com/rabobank-cdc/DeTTECT/tree/master/editor/src/data) 4 days ago. Also it looks like the MITRE ATT&CK has a major update recently which introduced new techniques and refactoring of Cloud providers. https://attack.mitre.org/matrices/enterprise/cloud/officesuite/

Perhaps this needs a significant update to the DeTT&CT framework as well. But I'm not sure how long will it take. I'm also waiting for it. It had unfortunately happened while I was doing my visibility coverage part after spending few weeks for the data sources mapping. :(

**Comment by roboticsea** [comment]
@rahulgk-mettle glad to know it's not just me. @rubinatorz you rock

**Comment by rubinatorz** [comment]
hi @rahulgk-mettle and @roboticsea 

It seems that our pipeline failed on some update of the MITRE STIX data. I fixed this, so all data sources are available again 🤓

**Comment by roboticsea** [comment]
@rubinatorz thank you sir :)

**Comment by rubinatorz** [comment]
@rahulgk-mettle 

Thanks for pointing to MITRE's refactoring of cloud providers. We have pipelines that integrate changes automatically, but for the platforms I had to remove the old ones and add the new ones in the Editor.

**Comment by rahulgk-mettle** [comment]
Thank you for quickly resolving the issue @rubinatorz. Just wanted to cross check should the platforms to be changes in DeTTECT datasources as well in https://github.com/rabobank-cdc/DeTTECT/blob/master/editor/src/data/data_source_platforms.json#L398? They still appear as O365, Azure AD, Google Workspace etc there while it is changed for ATT&CK datasources.

**Comment by rahulgk-mettle** [comment]
I have been getting the below error when generating techniques yaml from the datasource yaml. 
<img width="1716" alt="Screenshot 2024-11-06 at 12 34 33" src="https://github.com/user-attachments/assets/14680e96-ff94-4c2b-b9f1-2d25533516e5">

**Comment by rubinatorz** [comment]
You're completely right @rahulgk-mettle Yesterday I updated some manual changes for the Editor, but the CLI also needed some updates. I just did some fixes and all my unit-tests are now succeeding. I also changed the platforms for DeTT&CT data sources. I did not yet create a release yet, but the changes are in the main branch. Can you check if everything works now for you?

**Comment by rahulgk-mettle** [comment]
Thanks again @rubinatorz, the issue seems fixed now. I don't see any errors now and the auto update is mapping the office suite and Identity provider datasources to the respective techniques.
